import { Section, Text } from '@react-email/components';
import { render } from '@react-email/render';
import { createTranslator } from 'next-intl';
import { EmailLayout } from './_components/EmailLayout';
import { getMessagesFor } from '@/lib/i18n/messages';
import { defaultLocale, type Locale } from '@/lib/i18n/locales';
import type { RenderedEmail } from './types';

// The 2FA one-time-code email (Story MOTIR-1213 · Subtask MOTIR-1219). Sent
// when a user at the login challenge picks "email me a code" instead of their
// authenticator app, and dispatched from Better-Auth's `twoFactor` plugin
// `otpOptions.sendOTP` hook via the durable `email.send` job (lib/auth/index.ts
// — the template is content, the wiring dispatches).
//
// The expiry copy here MUST match `otpOptions.period` in lib/auth/index.ts — if
// you change one, change the other. It is a PROP rather than a literal so the
// two cannot silently drift: the caller passes the configured value.
//
// ⚠️ NO LINK, AND NO `PrimaryButton` — deliberately, against the shape every
// other template in this folder has. Each of the eight existing templates exists
// to get somebody to a URL, so each carries a CTA and a "or copy this link"
// fallback. A one-time code is the opposite: the recipient has ALREADY started
// the flow in a browser they are looking at, and the only thing they need from
// the mail is six digits to type back into it. Putting a clickable
// "Sign in to Motir" button next to a live authentication code trains exactly
// the reflex a credential-phishing mail relies on, so the mirror products
// (GitHub, Google, Atlassian) all ship this one link-free. That also means the
// dev-console provider's "link unredacted in the plain text" contract has
// nothing to preserve here — what the plain text must carry verbatim is the
// CODE, which `buildPlainText` puts on a line of its own.
//
// Localized via next-intl's synchronous createTranslator (rendering runs
// off-request, inside the email.send job); `locale` defaults to the base locale
// when absent.

// A minimal translator shape (satisfied by createTranslator's result).
type T = (key: string, values?: Record<string, string | number>) => string;

export interface TwoFactorOtpEmailProps {
  recipientName: string;
  /** The one-time code, already generated by the plugin. Rendered verbatim. */
  code: string;
  /** Minutes the code stays valid — mirrors `otpOptions.period`. */
  expiresInMinutes: number;
  locale?: Locale;
}

function TwoFactorOtpEmail({
  recipientName,
  code,
  expiresInMinutes,
  t,
}: TwoFactorOtpEmailProps & { t: T }) {
  return (
    <EmailLayout preview={t('preview')} footer={t('security')}>
      <Text style={greeting}>{t('greeting', { name: recipientName })}</Text>
      <Text style={lede}>{t('lede')}</Text>
      <Section style={codeRow}>
        <Text style={codeText}>{code}</Text>
      </Section>
      <Text style={expiry}>{t('expires', { minutes: expiresInMinutes })}</Text>
    </EmailLayout>
  );
}

const greeting = { fontSize: '16px', margin: '0 0 16px' };
const lede = { fontSize: '16px', margin: '0 0 24px' };
const codeRow = { margin: '0 0 24px' };
// Literal hex, like every other style object in this folder: an email is not
// the app, so the `--el-*` token layer CLAUDE.md mandates for components does
// not exist here — Gmail strips <style> and CSS custom properties never
// resolve. #111827 on the layout's hardcoded #ffffff body is 16.9:1.
const codeText = {
  fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  fontSize: '32px',
  fontWeight: 700 as const,
  letterSpacing: '6px',
  color: '#111827',
  margin: '0',
};
const expiry = { color: '#6b7280', fontSize: '14px', margin: '0 0 24px' };

export async function twoFactorOtpEmail(props: TwoFactorOtpEmailProps): Promise<RenderedEmail> {
  const locale = props.locale ?? defaultLocale;
  const t = createTranslator({
    locale,
    messages: getMessagesFor(locale),
    namespace: 'email.twoFactorOtp',
  }) as T;
  const html = await render(<TwoFactorOtpEmail {...props} t={t} />);
  return {
    subject: t('subject', { code: props.code }),
    text: buildPlainText(props, t),
    html,
  };
}

function buildPlainText(props: TwoFactorOtpEmailProps, t: T): string {
  return [
    t('greeting', { name: props.recipientName }),
    '',
    t('lede'),
    '',
    // The code on a line of its own, unadorned — the plain-text analogue of the
    // "link unredacted" contract. A dev-console reader greps this line.
    props.code,
    '',
    t('expires', { minutes: props.expiresInMinutes }),
    '',
    t('security'),
    '',
    '— Motir',
  ].join('\n');
}

export default TwoFactorOtpEmail;
