-- Make the four TENANT-ROOT tables creatable under the non-bypass role (MOTIR-2512).
--
-- THE DEFECT. `organization`, `organization_membership`, `workspace` and
-- `workspace_membership` are the only four of the 66 RLS-enabled `public` tables
-- with no policy admitting INSERT; every other one covers all four verbs. Under
-- `motir_app` that is not "ungated", it is DENIED:
--
--     ERROR:  new row violates row-level security policy for table "organization"
--
-- So sign-up and workspace creation are impossible as the runtime role, and the
-- whole point of MOTIR-2435 -- pointing production at that role -- would have
-- broken the product on its first request.
--
-- WHY IT LOOKED FINE. 20260527134009_add_workspace_rls records the reasoning:
-- "INSERT establishes a tenant rather than acting within one, so we can't
-- sensibly gate INSERT on the workspace GUC ... Authorization for who can INSERT
-- lives at the application layer." That decision is right, and this migration
-- does not overturn it. What it missed is that RLS has no "unguarded" setting:
-- ENABLE + no policy for a verb means that verb is refused. Application-layer
-- authorization still needs a policy that SAYS SO.
--
-- ⚠️ AND WHY THE OBVIOUS FIX IS WRONG. `FOR INSERT WITH CHECK (true)` makes a
-- bare INSERT succeed and `INSERT ... RETURNING` still fail, because Postgres
-- also applies the SELECT policies to the row it hands back. Prisma's `create()`
-- ALWAYS emits RETURNING, so the naive fix passes a psql probe and leaves the
-- application exactly as broken. Every policy below is paired so the row is
-- both insertable AND returnable.
--
-- THE PREDICATE, and why it is not a widening. A tenant-root row cannot be gated
-- on its own id: `@default(cuid())` is generated by Prisma, so the id does not
-- exist until the INSERT runs and cannot be bound to a GUC beforehand. The SLUG
-- can -- the caller chooses it, it is globally UNIQUE on both tables, and it is
-- known before the statement. So the creating transaction binds
-- `app.bootstrap_slug`, and these policies admit exactly the one row carrying it.
-- Outside such a transaction the GUC is unset, `current_setting(..., true)`
-- returns NULL, the predicate is NULL, and no row is insertable or visible --
-- the same safe failure mode every other policy here relies on.
--
-- ⚠️ THE MEMBERSHIP TABLES DO **NOT** REUSE THEIR SELECT/DELETE PREDICATE, and
-- the reason is worth stating because the symmetry is tempting. Those policies
-- read "the active tenant's rows, OR YOUR OWN", which is right for both: seeing
-- your own memberships anywhere is harmless, and deleting your own is how you
-- LEAVE a workspace. Copied onto INSERT the same clause means "you may add
-- YOURSELF to ANY workspace" -- self-join, which is an escalation, where
-- self-leave is not. Same words, opposite consequence.
--
-- So the second arm is the BOOTSTRAP one instead: the row may target the tenant
-- being established right now, identified by the same slug the tables above are
-- keyed on. That covers the founder's own owner-row, which is the only
-- membership that legitimately exists before any workspace context does, and
-- nothing else. The first arm -- acting inside the active tenant -- is what
-- repairs `workspacesService.addMember`, the invite flow, which is the same
-- missing-INSERT defect on the same table.
--
-- The runtime half is `insertWorkspaceWithOwner` in lib/services/workspacesService.ts,
-- which binds `app.user_id` + `app.bootstrap_slug` (and `app.organization_id` on
-- the nest-under-an-existing-org path) at the top of its transaction.

-- ── organization ────────────────────────────────────────────────────────────
-- The row being established, addressed by the slug the caller chose.
CREATE POLICY "organization_insert_bootstrap" ON "organization"
  FOR INSERT
  WITH CHECK (slug = current_setting('app.bootstrap_slug', true));

-- Its RETURNING counterpart. Without this the INSERT above succeeds and the
-- statement still errors, because the new row is invisible to the SELECT
-- policies (`organization_active` keys on app.organization_id, which cannot be
-- known yet, and `organization_membership_visible` keys on a membership row that
-- this transaction has not created yet).
CREATE POLICY "organization_visible_bootstrap" ON "organization"
  FOR SELECT
  USING (slug = current_setting('app.bootstrap_slug', true));

-- ── workspace ───────────────────────────────────────────────────────────────
-- Same pair, same reasoning. The workspace reuses the organization's slug on the
-- fresh-account path, and carries its own on the nest-under-an-org path; either
-- way the caller has it before the INSERT.
CREATE POLICY "workspace_insert_bootstrap" ON "workspace"
  FOR INSERT
  WITH CHECK (slug = current_setting('app.bootstrap_slug', true));

CREATE POLICY "workspace_visible_bootstrap" ON "workspace"
  FOR SELECT
  USING (slug = current_setting('app.bootstrap_slug', true));

-- ── organization_membership ─────────────────────────────────────────────────
-- Arm 1: acting inside the active organization (the ordinary path -- an org
-- member being added while an org context is bound).
-- Arm 2: the org being BOOTSTRAPPED right now, addressed by the same slug. This
-- is the founder's own owner-row, created before any org context can exist.
-- RETURNING is covered by the existing `org_membership_visible_active_or_own`,
-- whose "or your own" arm admits the founder's row.
CREATE POLICY "org_membership_insert_active_or_bootstrap" ON "organization_membership"
  FOR INSERT
  WITH CHECK (
    "organizationId" = current_setting('app.organization_id', true)
    OR "organizationId" IN (
      SELECT id FROM "organization" WHERE slug = current_setting('app.bootstrap_slug', true)
    )
  );

-- ── workspace_membership ────────────────────────────────────────────────────
-- Same two arms. Arm 1 is the INVITE path: an accept runs inside
-- withWorkspaceContext, so the active workspace is bound and a member may be
-- added to it. Arm 2 is the founder's owner-row during bootstrap.
--
-- Note what is deliberately NOT here: `OR "userId" = current_setting('app.user_id')`.
-- It would make the founder case trivially pass, and it would also let any user
-- insert their own membership into any workspace they can name.
CREATE POLICY "membership_insert_active_or_bootstrap" ON "workspace_membership"
  FOR INSERT
  WITH CHECK (
    "workspaceId" = current_setting('app.workspace_id', true)
    OR "workspaceId" IN (
      SELECT id FROM "workspace" WHERE slug = current_setting('app.bootstrap_slug', true)
    )
  );
