#!/usr/bin/env bash
# Install the system shared libraries Playwright's Chromium needs — WITHOUT
# root — into a per-user prefix. For dev containers where you can't rebuild
# the image or run `sudo playwright install-deps` (e.g. the agent sandbox runs
# as a non-root user with no passwordless sudo).
#
# CI does NOT need this: the Playwright job installs the deps system-wide with
# `playwright install --with-deps chromium` (root at build time). This is the
# no-root local-dev equivalent — it downloads the same .debs with
# `apt-get --download-only` and extracts them into $HOME, then exposes them via
# LD_LIBRARY_PATH (written to an env file you source before `pnpm test:e2e`).
#
# Idempotent: re-running it is a no-op once Chromium's libs already resolve.
# Usually you don't call this directly — `pnpm test:e2e:local` does it for you.
#
# Only supports Debian/Ubuntu (apt) containers — the only kind we ship.
set -euo pipefail

PREFIX_ROOT="${PRODECT_E2E_DEPS_DIR:-$HOME/.cache/prodect-e2e-deps}"
PREFIX="$PREFIX_ROOT/prefix"
ENV_FILE="$PREFIX_ROOT/env.sh"

if ! command -v apt-get >/dev/null 2>&1 || ! command -v dpkg-deb >/dev/null 2>&1; then
  echo "error: apt-get/dpkg-deb not found — this script only supports Debian/Ubuntu." >&2
  echo "       With root, prefer: pnpm exec playwright install --with-deps chromium" >&2
  exit 1
fi

# Multiarch triplet (e.g. x86_64-linux-gnu / aarch64-linux-gnu), derived from
# the system lib layout so nothing is hardcoded to one architecture.
MULTIARCH="$(basename "$(ls -d /usr/lib/*-linux-gnu 2>/dev/null | head -1 || true)")"
if [ -z "$MULTIARCH" ]; then
  echo "error: could not determine the multiarch lib triplet (/usr/lib/*-linux-gnu)." >&2
  exit 1
fi
LD_PREFIX="$PREFIX/usr/lib/$MULTIARCH:$PREFIX/lib/$MULTIARCH"

write_env_file() {
  mkdir -p "$PREFIX_ROOT"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/e2e-browser-deps.sh — source before \`pnpm test:e2e\`.
export LD_LIBRARY_PATH="$LD_PREFIX\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
EOF
}

# A Playwright browser binary to ldd-check (chromium or the headless shell).
BROWSER="$(find "$HOME/.cache/ms-playwright" -type f \( -name chrome -o -name headless_shell \) 2>/dev/null | head -1 || true)"
if [ -z "$BROWSER" ]; then
  echo "==> No Playwright browser found under ~/.cache/ms-playwright." >&2
  echo "    Run 'pnpm exec playwright install chromium' first, then re-run this." >&2
  exit 1
fi

libs_resolve() {
  ! LD_LIBRARY_PATH="$LD_PREFIX:${LD_LIBRARY_PATH:-}" ldd "$BROWSER" 2>/dev/null | grep -q "not found"
}

# Fast path: already satisfied (system libs and/or a previous run's prefix).
if libs_resolve; then
  write_env_file
  echo "==> Chromium's system libraries already resolve — nothing to install."
  echo "==> Wrote $ENV_FILE"
  exit 0
fi

echo "==> Installing Chromium system libs into $PREFIX (no root)…"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/lists/partial" "$WORK/cache/archives/partial" "$PREFIX"

# Run apt entirely in user-writable dirs; point Dir::State::status at the real
# dpkg DB so only genuinely-missing packages (and their transitive deps) are
# fetched, not the whole closure.
APT_OPTS=(
  -o Dir::Etc::sourcelist=/etc/apt/sources.list
  -o Dir::Etc::sourceparts=/etc/apt/sources.list.d
  -o Dir::Etc::trustedparts=/etc/apt/trusted.gpg.d
  -o Dir::State::lists="$WORK/lists"
  -o Dir::State::status=/var/lib/dpkg/status
  -o Dir::Cache="$WORK/cache"
  -o Dir::Cache::archives="$WORK/cache/archives"
  -o Debug::NoLocking=true
)

# Chromium's runtime deps (Debian/Ubuntu package names). apt resolves the rest.
PKGS=(
  libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libatspi2.0-0 libcups2
  libdbus-1-3 libgbm1 libxkbcommon0 libasound2 libxcomposite1 libxdamage1
  libxfixes3 libxrandr2 libxrender1 libxext6 libxcb1 libx11-6 libexpat1
  libxcursor1 libxi6 libpango-1.0-0 libcairo2
)

apt-get "${APT_OPTS[@]}" update
apt-get "${APT_OPTS[@]}" -y --download-only --no-install-recommends install "${PKGS[@]}"

shopt -s nullglob
for deb in "$WORK"/cache/archives/*.deb; do
  dpkg-deb -x "$deb" "$PREFIX"
done
shopt -u nullglob

if ! libs_resolve; then
  echo "error: some libraries are still unresolved after install:" >&2
  LD_LIBRARY_PATH="$LD_PREFIX:${LD_LIBRARY_PATH:-}" ldd "$BROWSER" 2>/dev/null | grep "not found" >&2 || true
  exit 1
fi

write_env_file
echo "==> Done — Chromium's libraries now resolve. Wrote $ENV_FILE"
