import type { IdeaCategory, IdeaKind } from '@/generated/prisma/client';
import type { IdeaTranslationLocale } from '@/lib/ideas/translatableFields';

/**
 * The display label of every idea category (Story MOTIR-7662). A
 * `Record<IdeaCategory, string>`, so adding a value to the Prisma enum without
 * a label here is a compile error rather than a blank chip on motir.co.
 */
export const IDEA_CATEGORY_LABELS: Record<IdeaCategory, string> = {
  legal: 'Legal',
  finance: 'Finance',
  security_compliance: 'Security & compliance',
  customer_support: 'Customer support',
  localization: 'Localization',
  growth_marketing: 'Growth & marketing',
  sales: 'Sales',
  people_hr: 'People & HR',
  operations: 'Operations',
  engineering: 'Engineering',
  ecommerce: 'E-commerce',
  healthcare: 'Healthcare',
  education: 'Education',
  financial_services: 'Financial services',
  real_estate: 'Real estate',
  logistics: 'Logistics',
  construction: 'Construction',
  agriculture: 'Agriculture',
  pets: 'Pets',
  family_care: 'Family care',
  public_sector: 'Public sector',
  personal_growth: 'Personal growth',
  personal_finance: 'Personal finance',
  health_wellness: 'Health & wellness',
  ai_infrastructure: 'AI infrastructure',
};

/**
 * The label of every category in each of the ten translation locales (bug
 * MOTIR-8082). A total `Record<IdeaTranslationLocale, Record<IdeaCategory,
 * string>>`, so a new enum value without all ten labels — or a new locale
 * without its column — is a compile error. English is `IDEA_CATEGORY_LABELS`.
 */
export const IDEA_CATEGORY_TRANSLATIONS: Record<
  IdeaTranslationLocale,
  Record<IdeaCategory, string>
> = {
  zh: {
    legal: '法务',
    finance: '财务',
    security_compliance: '安全与合规',
    customer_support: '客户支持',
    localization: '本地化',
    growth_marketing: '增长与营销',
    sales: '销售',
    people_hr: '人事与人力资源',
    operations: '运营',
    engineering: '工程',
    ecommerce: '电子商务',
    healthcare: '医疗健康',
    education: '教育',
    financial_services: '金融服务',
    real_estate: '房地产',
    logistics: '物流',
    construction: '建筑',
    agriculture: '农业',
    pets: '宠物',
    family_care: '家庭护理',
    public_sector: '公共部门',
    personal_growth: '个人成长',
    personal_finance: '个人理财',
    health_wellness: '健康与养生',
    ai_infrastructure: 'AI 基础设施',
  },
  ja: {
    legal: '法務',
    finance: '財務',
    security_compliance: 'セキュリティとコンプライアンス',
    customer_support: 'カスタマーサポート',
    localization: 'ローカライズ',
    growth_marketing: 'グロースとマーケティング',
    sales: '営業',
    people_hr: '人事',
    operations: 'オペレーション',
    engineering: 'エンジニアリング',
    ecommerce: 'Eコマース',
    healthcare: 'ヘルスケア',
    education: '教育',
    financial_services: '金融サービス',
    real_estate: '不動産',
    logistics: '物流',
    construction: '建設',
    agriculture: '農業',
    pets: 'ペット',
    family_care: '家族のケア',
    public_sector: '公共セクター',
    personal_growth: '自己成長',
    personal_finance: '個人の資産管理',
    health_wellness: '健康とウェルネス',
    ai_infrastructure: 'AIインフラ',
  },
  ko: {
    legal: '법무',
    finance: '재무',
    security_compliance: '보안 및 컴플라이언스',
    customer_support: '고객 지원',
    localization: '현지화',
    growth_marketing: '그로스 및 마케팅',
    sales: '영업',
    people_hr: '인사',
    operations: '운영',
    engineering: '엔지니어링',
    ecommerce: '전자상거래',
    healthcare: '헬스케어',
    education: '교육',
    financial_services: '금융 서비스',
    real_estate: '부동산',
    logistics: '물류',
    construction: '건설',
    agriculture: '농업',
    pets: '반려동물',
    family_care: '가족 돌봄',
    public_sector: '공공 부문',
    personal_growth: '자기 계발',
    personal_finance: '개인 재무',
    health_wellness: '건강 및 웰니스',
    ai_infrastructure: 'AI 인프라',
  },
  de: {
    legal: 'Recht',
    finance: 'Finanzen',
    security_compliance: 'Sicherheit und Compliance',
    customer_support: 'Kundensupport',
    localization: 'Lokalisierung',
    growth_marketing: 'Wachstum und Marketing',
    sales: 'Vertrieb',
    people_hr: 'Personal',
    operations: 'Betrieb',
    engineering: 'Engineering',
    ecommerce: 'E-Commerce',
    healthcare: 'Gesundheitswesen',
    education: 'Bildung',
    financial_services: 'Finanzdienstleistungen',
    real_estate: 'Immobilien',
    logistics: 'Logistik',
    construction: 'Bauwesen',
    agriculture: 'Landwirtschaft',
    pets: 'Haustiere',
    family_care: 'Familienpflege',
    public_sector: 'Öffentlicher Sektor',
    personal_growth: 'Persönliche Entwicklung',
    personal_finance: 'Private Finanzen',
    health_wellness: 'Gesundheit und Wellness',
    ai_infrastructure: 'KI-Infrastruktur',
  },
  fr: {
    legal: 'Juridique',
    finance: 'Finance',
    security_compliance: 'Sécurité et conformité',
    customer_support: 'Support client',
    localization: 'Localisation',
    growth_marketing: 'Croissance et marketing',
    sales: 'Ventes',
    people_hr: 'Personnes et RH',
    operations: 'Opérations',
    engineering: 'Ingénierie',
    ecommerce: 'E-commerce',
    healthcare: 'Santé',
    education: 'Éducation',
    financial_services: 'Services financiers',
    real_estate: 'Immobilier',
    logistics: 'Logistique',
    construction: 'Construction',
    agriculture: 'Agriculture',
    pets: 'Animaux de compagnie',
    family_care: 'Soins aux proches',
    public_sector: 'Secteur public',
    personal_growth: 'Développement personnel',
    personal_finance: 'Finances personnelles',
    health_wellness: 'Santé et bien-être',
    ai_infrastructure: 'Infrastructure IA',
  },
  es: {
    legal: 'Legal',
    finance: 'Finanzas',
    security_compliance: 'Seguridad y cumplimiento',
    customer_support: 'Atención al cliente',
    localization: 'Localización',
    growth_marketing: 'Crecimiento y marketing',
    sales: 'Ventas',
    people_hr: 'Personas y RR. HH.',
    operations: 'Operaciones',
    engineering: 'Ingeniería',
    ecommerce: 'Comercio electrónico',
    healthcare: 'Salud',
    education: 'Educación',
    financial_services: 'Servicios financieros',
    real_estate: 'Inmobiliaria',
    logistics: 'Logística',
    construction: 'Construcción',
    agriculture: 'Agricultura',
    pets: 'Mascotas',
    family_care: 'Cuidado familiar',
    public_sector: 'Sector público',
    personal_growth: 'Desarrollo personal',
    personal_finance: 'Finanzas personales',
    health_wellness: 'Salud y bienestar',
    ai_infrastructure: 'Infraestructura de IA',
  },
  it: {
    legal: 'Legale',
    finance: 'Finanza',
    security_compliance: 'Sicurezza e conformità',
    customer_support: 'Assistenza clienti',
    localization: 'Localizzazione',
    growth_marketing: 'Crescita e marketing',
    sales: 'Vendite',
    people_hr: 'Persone e risorse umane',
    operations: 'Operazioni',
    engineering: 'Ingegneria',
    ecommerce: 'E-commerce',
    healthcare: 'Sanità',
    education: 'Istruzione',
    financial_services: 'Servizi finanziari',
    real_estate: 'Immobiliare',
    logistics: 'Logistica',
    construction: 'Edilizia',
    agriculture: 'Agricoltura',
    pets: 'Animali domestici',
    family_care: 'Assistenza familiare',
    public_sector: 'Settore pubblico',
    personal_growth: 'Crescita personale',
    personal_finance: 'Finanza personale',
    health_wellness: 'Salute e benessere',
    ai_infrastructure: 'Infrastruttura IA',
  },
  nl: {
    legal: 'Juridisch',
    finance: 'Financiën',
    security_compliance: 'Beveiliging en compliance',
    customer_support: 'Klantondersteuning',
    localization: 'Lokalisatie',
    growth_marketing: 'Groei en marketing',
    sales: 'Verkoop',
    people_hr: 'Mensen en HR',
    operations: 'Operations',
    engineering: 'Engineering',
    ecommerce: 'E-commerce',
    healthcare: 'Gezondheidszorg',
    education: 'Onderwijs',
    financial_services: 'Financiële diensten',
    real_estate: 'Vastgoed',
    logistics: 'Logistiek',
    construction: 'Bouw',
    agriculture: 'Landbouw',
    pets: 'Huisdieren',
    family_care: 'Gezinszorg',
    public_sector: 'Publieke sector',
    personal_growth: 'Persoonlijke groei',
    personal_finance: 'Persoonlijke financiën',
    health_wellness: 'Gezondheid en welzijn',
    ai_infrastructure: 'AI-infrastructuur',
  },
  pl: {
    legal: 'Prawo',
    finance: 'Finanse',
    security_compliance: 'Bezpieczeństwo i zgodność',
    customer_support: 'Obsługa klienta',
    localization: 'Lokalizacja',
    growth_marketing: 'Wzrost i marketing',
    sales: 'Sprzedaż',
    people_hr: 'Ludzie i HR',
    operations: 'Operacje',
    engineering: 'Inżynieria',
    ecommerce: 'E-commerce',
    healthcare: 'Opieka zdrowotna',
    education: 'Edukacja',
    financial_services: 'Usługi finansowe',
    real_estate: 'Nieruchomości',
    logistics: 'Logistyka',
    construction: 'Budownictwo',
    agriculture: 'Rolnictwo',
    pets: 'Zwierzęta domowe',
    family_care: 'Opieka rodzinna',
    public_sector: 'Sektor publiczny',
    personal_growth: 'Rozwój osobisty',
    personal_finance: 'Finanse osobiste',
    health_wellness: 'Zdrowie i dobre samopoczucie',
    ai_infrastructure: 'Infrastruktura AI',
  },
  pt: {
    legal: 'Jurídico',
    finance: 'Finanças',
    security_compliance: 'Segurança e conformidade',
    customer_support: 'Suporte ao cliente',
    localization: 'Localização',
    growth_marketing: 'Crescimento e marketing',
    sales: 'Vendas',
    people_hr: 'Pessoas e RH',
    operations: 'Operações',
    engineering: 'Engenharia',
    ecommerce: 'Comércio eletrônico',
    healthcare: 'Saúde',
    education: 'Educação',
    financial_services: 'Serviços financeiros',
    real_estate: 'Imobiliário',
    logistics: 'Logística',
    construction: 'Construção',
    agriculture: 'Agricultura',
    pets: 'Animais de estimação',
    family_care: 'Cuidado familiar',
    public_sector: 'Setor público',
    personal_growth: 'Desenvolvimento pessoal',
    personal_finance: 'Finanças pessoais',
    health_wellness: 'Saúde e bem-estar',
    ai_infrastructure: 'Infraestrutura de IA',
  },
};

/** A category's label in `locale`; `en` is the English label. */
export function ideaCategoryLabel(
  category: IdeaCategory,
  locale: 'en' | IdeaTranslationLocale,
): string {
  return locale === 'en'
    ? IDEA_CATEGORY_LABELS[category]
    : IDEA_CATEGORY_TRANSLATIONS[locale][category];
}

/** Every category, in the enum's (grouped) order. */
export const IDEA_CATEGORIES = Object.keys(IDEA_CATEGORY_LABELS) as IdeaCategory[];

/** Every kind. `motir_buys` first — the order the public list sorts by. */
export const IDEA_KINDS: readonly IdeaKind[] = ['motir_buys', 'direction'];

export function isIdeaCategory(value: string): value is IdeaCategory {
  return Object.hasOwn(IDEA_CATEGORY_LABELS, value);
}

export function isIdeaKind(value: string): value is IdeaKind {
  return (IDEA_KINDS as readonly string[]).includes(value);
}

/** The slug shape every idea and tag slug takes: lowercase words joined by `-`. */
export const IDEA_SLUG_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
export const IDEA_SLUG_MAX = 80;
